### ISSUE TITLE
Звуковые сообщения о новых ивентах

### ISSUE THREAD

**Issue by DdenisovReserved** [inilotic/vks_nodes_core#15]
-короткое и негромкое о новой заявке
-более длинное и громкое для начала записи+окно предупреждение красным
-более длинное и громкое для начала важной ВКС+окно предупреждение красным

Если у тебя нет библиотеки звуков под рукой, скажи мне, я сам подберу что-нибудь (скажи только о требуемом формате файла)

**Comment by inilotic** [comment]
реализовано в 0.4.83
