### ISSUE TITLE
некорректная логика добавления события в календарь

### ISSUE THREAD

**Issue by DdenisovReserved** [inilotic/vks_nodes_core#27]
Я отправил заявку.
Мне пришло на почту сообщение о том, что заявка отправлена, ожидайте согласование.
В почте есть кнопка "добавить событие в календарь". Пользователь нажимает на нее и видит ошибку 404 и пояснения "возможно, ВКС не согласована и поэтому вы не можете добавить ее в календарь".

Нужно обсудить как выйдем из ситуации

**Comment by inilotic** [comment]
не баг, а фича. Такие письма приходят всем админам при создании ВКС. Поправил шаблон.
