### ISSUE TITLE
Случайная пре-генерация кода при согласовании ВКС 

### ISSUE THREAD

**Issue by inilotic** [inilotic/vks_nodes_core#9]
Опция отключаема в настройках

**Comment by DdenisovReserved** [comment]
Два доп. момента:
1) Пре-генерация кода должна быть случайной, но не пересекаться по номеру с уже идущими ВКС
2) Если у нас нескольо конференций в одном стеке, пре-генерация кода должна проходить с учетом всех заявленных конференций

**Comment by inilotic** [comment]
генерация случайного кода проходит с учетом занятости, если выданный случайный код занят где-то он не может быть выдан.
